export const userRoles = [
  {value: 'student', label: 'Student'},
  {value: 'mentor', label: 'Mentor'},
]

export const Roles = Object.freeze({
  STUDENT: 'student',
  MENTOR: 'mentor',
})

export const skills = [
  {label: 'IT Skills', value: 147},
  {label: 'BPO', value: 167},
  {label: 'Sales', value: 100},
  {label: 'Java', value: 805},
  {label: 'communication', value: 25},
  {label: 'team handling', value: 447},
  {label: 'Cloud', value: 172},
  {label: 'Javascript', value: 1830},
  {label: 'Python', value: 522},
  {label: 'Testing', value: 148},
  {label: 'tied', value: 537},
  {label: 'agency', value: 538},
  {label: 'voice', value: 988},
  {label: 'HTML', value: 124},
  {label: 'sales', value: 35},
  {label: 'Customer Service', value: 279},
  {label: 'Agile', value: 184},
  {label: 'BFSI', value: 103},
  {label: 'Analytical', value: 52},
  {label: 'Management', value: 134},
  {label: 'Bancassurance', value: 104},
  {label: 'SQL', value: 250},
  {label: 'SAP', value: 1437},
  {label: 'Life Insurance', value: 111},
  {label: 'Linux', value: 1039},
  {label: 'Automation', value: 38},
  {label: 'CSS', value: 1833},
  {label: 'training', value: 3884},
  {label: 'agency channel', value: 1000},
  {label: 'Excel', value: 78},
  {label: 'AWS', value: 807},
  {label: 'bfsi', value: 1052},
  {label: 'branch management', value: 1368},
  {label: 'advisors', value: 22697},
  {label: 'Networking', value: 393},
  {label: 'customer service', value: 592},
  {label: 'Azure', value: 1902},
  {label: 'Training', value: 132},
  {label: 'Consulting', value: 2},
  {label: 'banking', value: 65},
  {label: 'Oracle', value: 146},
  {label: 'Channel Management', value: 515},
  {label: 'Business Development', value: 248},
  {label: 'bank branches', value: 516},
  {label: 'Software Development', value: 251},
  {label: 'Voice Process', value: 166},
  {label: 'Communication Skills', value: 491},
  {label: 'Project management', value: 142},
  {label: 'Finance', value: 54},
  {label: 'analytical', value: 9},
  {label: 'MySQL', value: 1456},
  {label: 'Project Management', value: 844},
  {label: 'Fund accounting', value: 379},
  {label: 'Accounting', value: 66},
  {label: 'Customer Support', value: 578},
  {label: 'Angular', value: 5815},
  {label: 'Operations', value: 47},
  {label: 'Troubleshooting', value: 85},
  {label: 'HR', value: 527},
  {label: 'Customer service', value: 283},
  {label: 'PHP', value: 6422},
  {label: 'MS Office', value: 121},
  {label: 'written', value: 687},
  {label: 'DevOps', value: 952},
  {label: 'Marketing', value: 293},
  {label: 'Jenkins', value: 5640},
  {label: 'verbal', value: 688},
  {label: 'Coding', value: 967},
  {label: 'Loans', value: 42},
  {label: 'Telesales', value: 165},
  {label: 'Communication', value: 647},
  {label: 'Monitoring', value: 64},
  {label: 'XML', value: 2449},
  {label: 'Interpersonal skills', value: 127},
  {label: 'Banking', value: 113},
  {label: 'agent', value: 536},
  {label: 'Administration', value: 221},
  {label: 'International Call Center', value: 1302},
  {label: 'Recruitment', value: 399},
  {label: 'business', value: 475},
  {label: 'direct', value: 541},
  {label: 'channel', value: 540},
  {label: 'team', value: 542},
  {label: 'dst', value: 539},
  {label: 'Team Handling', value: 289},
  {label: 'C#', value: 855},
  {label: 'Business process', value: 162},
  {label: 'C++', value: 3790},
  {label: 'Unix', value: 1036},
  {label: 'SAN', value: 261},
  {label: 'Data analysis', value: 48},
  {label: 'project management', value: 178},
  {label: 'ERP', value: 1749},
  {label: 'written communication', value: 88},
  {label: 'inbound', value: 168},
  {label: 'Compliance', value: 232},
  {label: 'Scrum', value: 2932},
  {label: 'GIT', value: 5230},
  {label: 'jQuery', value: 6298},
  {label: 'Debugging', value: 2857},
]

export const careerCategories = {
  'BFSI, Investments & Trading': 0,
  'Customer Success, Service & Operations': 1,
  'Data Science & Analytics': 2,
  'Engineering - Hardware & Networks': 3,
  'Engineering - Software & QA': 4,
  'Finance & Accounting': 5,
  'Human Resources': 6,
  'IT & Information Security': 7,
  'Marketing & Communication': 8,
  'Product Management': 9,
  'Production, Manufacturing & Engineering': 10,
  'Project & Program Management': 11,
  'Quality Assurance': 12,
  'Sales & Business Development': 13,
  'UX, Design & Architecture': 14,
  'Administration & Facilities': 15,
  'Aviation & Aerospace': 16,
  'Construction & Site Engineering': 17,
  Consulting: 18,
  'Content, Editorial & Journalism': 19,
  'CSR & Social Service': 20,
  'Energy & Mining': 21,
  'Environment Health & Safety': 22,
  'Food, Beverage & Hospitality': 23,
  'Healthcare & Life Sciences': 24,
  'Legal & Regulatory': 25,
  'Media Production & Entertainment': 26,
  'Merchandising, Retail & eCommerce': 27,
  'Procurement & Supply Chain': 28,
  'Research & Development': 29,
  'Risk Management & Compliance': 30,
  'Security Services': 31,
  Other: 32,
  'Sports, Fitness & Personal Care': 33,
  'Strategic & Top Management': 34,
  'Teaching & Training': 35,
  'Shipping & Maritime': 36,
}

export const jobTitle = {
  'Applications Developer': 0,
  'CRM Technical Developer': 1,
  'Database Developer': 2,
  'Mobile Applications Developer': 3,
  'Network Security Engineer': 4,
  'Software Developer': 5,
  'Software Engineer': 6,
  'Software Quality Assurance (QA) / Testing': 7,
  'Systems Security Administrator': 8,
  'Technical Support': 9,
  'UX Designer': 10,
  'Web Developer': 11,
}

export const softSkillMapping = {
  'Applications Developer': 'Electron,TFLite,kotlin,React Native',
  'CRM Technical Developer': 'Dashboard,Analysis,SQL,Python',
  'Database Developer': 'SQL,MySQL,Oracle,PostgreSQL',
  'Mobile Applications Developer': 'Android,Flutter,kotlin,React Native',
  'Network Security Engineer': 'Networking,Firewall,VPN,Network Security,CCNA,CCNP',
  'Software Developer': 'HTML,CSS,JavaScript,PHP,SAP,Desktop Application',
  'Software Engineer': 'Python,Java,JavaScript,PHP,SAP,Desktop Application',
  'Software Quality Assurance (QA) / Testing': 'Automation,Manual,Testing,QA',
  'Systems Security Administrator': 'Networking,Firewall,VPN,Network Security,CCNA,CCNP',
  'Technical Support': 'Troubleshooting,Windows,Desktop Support,IT Helpdesk',
  'UX Designer': 'UI,UX,Adobe XD,Figma,Adobe Photoshop,Adobe Illustrator',
  'Web Developer': 'Reactjs,MERN stack,LAMP stack,Angularjs,SAP,Desktop Application',
}
